[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    mobizt/Firebase ESP32 Client @ ^4.4.14
    madhephaestus/ESP32Servo @ ^1.1.0
    bogde/HX711 @ ^0.7.5
    bblanchon/ArduinoJson @ ^6.21.3
    adafruit/DHT sensor library@^1.4.4