[wokwi]
version = 1
firmware = '.pio/build/esp32dev/firmware.bin'
elf = '.pio/build/esp32dev/firmware.elf'

# Tambahin baris di bawah ini:
libraries = [
  "ESP32Servo",
  "HX711",
  "Firebase ESP32 Client",
  "ArduinoJson"  #  komunikasi data ke Firebase
]
